import { QueryLogItem } from '../../types';

export const testQueryLogItems: QueryLogItem[] = [
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'exampleexampleexampleexampleexample.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'exampleexampleexampleexampleexample_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'exampleexampleexampleexampleexample',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'exampleexampleexampleexampleexample.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'exampleexampleexampleexampleexample_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'exampleexampleexampleexampleexample',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'exampleexampleexampleexampleexample.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'exampleexampleexampleexampleexample_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
  {
    asn: 12345,
    category_type: 'example',
    client_country: 'US',
    company_id: 'abc123',
    device_id: 'def456',
    dns_proto_type: 'UDP',
    dns_request_type: 'A',
    dns_response_type: 'A',
    dnssec: true,
    domain: 'example.com',
    filtering_info: {
      blocked_service_id: 'xyz789',
      filter_id: 'filter123',
      filter_rule: 'block',
      filtering_status: 'REQUEST_BLOCKED',
      filtering_type: 'content',
    },
    network: 'example_network',
    response_country: 'US',
    time_iso: '2023-05-19T12:34:56Z',
    time_millis: 1621420496000,
  },
];
